name: xlib_think_ext
version: 0.1.1
description: >
  Common Libraries Accumulates on thinking Web Foundations
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://www.thinking-grp.org
repository: https://github.com/thinking-grp/thinking-grp.github.io
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  web: ^1.1.1
  yaml: ^3.1.3
  markdown: ^7.3.0
topics:
  - thinking-grp
  - website
  - library
publish_to: none
